# Generated by Django 4.2.11 on 2024-05-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Cooking',
            field=models.CharField(default='unspecified', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='Meat',
            field=models.CharField(default='unspecified', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='Region',
            field=models.CharField(default='unspecified', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='favoriteCooking',
            field=models.CharField(default='unspecified', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='favoriteMeat',
            field=models.CharField(default='unspecified', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='favoriteRegion',
            field=models.CharField(default='unspecified', max_length=100),
        ),
    ]
