# Generated by Django 4.2.11 on 2024-05-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_cooking_post_meat_post_region_post_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
