# Generated by Django 5.0.4 on 2024-05-09 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="active",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="name",
        ),
    ]
