# Generated by Django 5.0.4 on 2024-05-14 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_message_room"),
        ("core", "0009_profile_birthdate"),
    ]

    operations = []
