# Generated by Django 4.1 on 2024-05-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_message_room'),
        ('core', '0009_profile_birthdate'),
    ]

    operations = [
    ]
