# Generated by Django 5.0.4 on 2024-05-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_threadmodel_messagemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="username",
            field=models.CharField(default="unknown", max_length=100),
        ),
    ]
