# Generated by Django 5.0.4 on 2024-05-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_threadmodel_messagemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user_comment",
            field=models.TextField(default=1000),
            preserve_default=False,
        ),
    ]
