# Generated by Django 4.1 on 2024-05-21 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_threadmodel_messagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
