# Generated by Django 4.1 on 2024-05-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_comment_username'),
        ('core', '0012_likepost_created_on'),
    ]

    operations = [
    ]
