# Generated by Django 5.0.6 on 2024-05-24 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_comment_username'),
        ('core', '0012_likepost_created_on'),
    ]

    operations = [
    ]
