# Generated by Django 5.0.4 on 2024-05-20 19:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_comment_user_comment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="PostComment",
        ),
    ]
