# Generated by Django 4.1 on 2024-05-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_0012_comment_username_0012_likepost_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Meat',
            new_name='Spicyness',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Region',
            new_name='Origin',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='favoriteMeat',
            new_name='favoriteSpicyness',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='favoriteRegion',
            new_name='favoriteOrigin',
        ),
    ]
