# Generated by Django 4.1 on 2024-05-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_meat_post_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Cooking',
            field=models.CharField(default='burnt', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='Origin',
            field=models.CharField(default='Leftovers', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='Spicyness',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favoriteCooking',
            field=models.CharField(default='burnt', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favoriteOrigin',
            field=models.CharField(default='Leftovers', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favoriteSpicyness',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
