# Generated by Django 5.0.6 on 2024-05-25 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_meat_post_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followerscount',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='likepost',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
