# Generated by Django 5.0.6 on 2024-05-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_post_cooking_alter_post_origin_and_more'),
        ('core', '0016_rename_created_on_followerscount_date'),
    ]

    operations = [
    ]
