# Generated by Django 5.0.6 on 2024-05-26 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20240526_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
